[server]
headless = true
port = 8501
enableCORS = false

[theme]
primaryColor = "#0C6DFD"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F2F2F2"
textColor = "#262730"
font = "sans serif"

[client]
toolbarMode = "minimal"
showSidebarNavigation = false
